local timer_config = 
{
	ARENA_SAVE_INTERVAL = 60,
	ARENA_DAY_REFRESH_INTERVAL = 86400,
	ARENA_DAY_REFRESH_HOUR = 0,
	ARENA_DAY_REFRESH_MIN = 0,
	ARENA_WEEK_REFRESH_INTERVAL = 86400 * 7,
	ARENA_WEEK_REFRESH_DAY = 2,
	ARENA_WEEK_REFRESH_HOUR = 0,
	ARENA_WEEK_REFRESH_MIN = 0,

}

g_timer_config = timer_config

return g_timer_config